version: "3.2"
services:
  # ------- Apache -------- #
  apache:
    build: './apache/'
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
    volumes:
      - ./public_html/:/var/www/html/
  # ------- PHP -------- #
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  # ------- MYSQL-------- #
  mysql:
    build: './mysql/'
    # image: mysql:3.5.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=hello1
      - MYSQL_DATABASE=employees
    volumes:
      - ./sql-scripts/:/docker-entrypoint-initdb.d/
  # ---- PHPMYADMIN UI ------- #
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend 
    ports:
      - "8082:80"
    environment:
      - PMA_ARBITRARY=1
      - TESTSUITE_PASSWORD=hello1
networks:
  frontend:
  backend:
