version: "3.2"
services:
  apache:
    build: './apache/'
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
    volumes:
      - ./public_html/:/var/www/html/
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
networks:
  frontend:
  backend:
